"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRouter = void 0;
const express_1 = require("express");
const controllers_1 = require("../controllers");
const middlewares_1 = require("../middlewares");
const validations_1 = require("../validations");
const router = (0, express_1.Router)();
router.post("/register", middlewares_1.commonMiddleware.isBodyValid(validations_1.userSchema.create), middlewares_1.authMiddleware.uniqueEmail, controllers_1.authController.register);
router.post("/login", middlewares_1.commonMiddleware.isBodyValid(validations_1.userSchema.login), middlewares_1.authMiddleware.loginError, controllers_1.authController.login);
router.post("/refreshToken", controllers_1.authController.refreshToken);
router.get("/current", middlewares_1.authenticateMiddleware.isLogin, controllers_1.authController.currentUser);
router.patch("/update", middlewares_1.authenticateMiddleware.isLogin, controllers_1.authController.updateUser);
router.delete("/logout", middlewares_1.authenticateMiddleware.isLogin, controllers_1.authController.logout);
exports.authRouter = router;
