"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = void 0;
const express_1 = require("express");
const controllers_1 = require("../controllers");
const middlewares_1 = require("../middlewares");
const validations_1 = require("../validations");
const router = (0, express_1.Router)();
router.get("/", controllers_1.userController.findAll);
router.post("/", middlewares_1.commonMiddleware.isBodyValid(validations_1.userSchema.create), controllers_1.userController.create);
router.get("/:userId", middlewares_1.commonMiddleware.isIdValid("userId"), middlewares_1.userMiddleware.findByIdByThrow, controllers_1.userController.findById);
router.put("/:userId", middlewares_1.commonMiddleware.isIdValid("userId"), middlewares_1.commonMiddleware.isBodyValid(validations_1.userSchema.create), middlewares_1.userMiddleware.findByIdByThrow, controllers_1.userController.updateByIdPut);
router.patch("/:userId", middlewares_1.commonMiddleware.isIdValid("userId"), middlewares_1.commonMiddleware.isBodyValid(validations_1.userSchema.updateUserSchema), middlewares_1.userMiddleware.findByIdByThrow, controllers_1.userController.updateByIdPatch);
router.delete("/:userId", middlewares_1.commonMiddleware.isIdValid("userId"), middlewares_1.userMiddleware.findByIdByThrow, controllers_1.userController.deleteById);
exports.userRouter = router;
